spring:
  mysql:
    datasource:
      url: jdbc:mysql://localhost:3306/studentdb
      username: root
      password: root
      driver-class-name: com.mysql.cj.jdbc.Driver
    jpa:
      properties:
        hibernate:
          dialect: org.hibernate.dialect.MySQLDialect

  postgres:
    datasource:
      url: jdbc:postgresql://localhost:5432/studentinfo
      username: postgres
      password: root
      driver-class-name: org.postgresql.Driver
    jpa:
      properties:
        hibernate:
          dialect: org.hibernate.dialect.PostgreSQLDialect
